# -*- coding: utf-8 -*-
"""NiAIipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uNaCIA1MUzcz3iFzaj6C8Pmcn1_o7cJ
"""

import numpy as np
import matplotlib.pyplot as plt

# 读取 phb 输出
data = np.loadtxt('phase_645_40.out')
T = data[:, 0]
x1 = 4.876 * data[:, 2] + 44.475
x2 = 4.876 * data[:, 3] + 44.475

# 画图（限制浓度范围）
plt.plot(x1, T, 'o-', label='x1 (phase α)')
plt.plot(x2, T, 'o-', label='x2 (phase β)')
plt.xlabel('Concentration x')
plt.ylabel('Temperature / K')
plt.title('Phase diagram from phb')
plt.xlim(30, 60)
 # ← 这里设置为论文的浓度范围
plt.ylim(0, max(T)*1.05)
plt.legend()
plt.grid(True)
plt.show()

#!/usr/bin/env python
import numpy
import matplotlib.pyplot as plt

#read data file
datafile=numpy.loadtxt('phase01.out')
T=list(datafile[:,0])
x1=list((datafile[:,2]+1)/2)
x2=list((datafile[:,3]+1)/2)

T+=list(reversed(T))
x=x1+list(reversed(x2))

plt.plot(x,T,linewidth=2.5)
#plt.scatter(x,T)
#plt.scatter(x1,T)
#plt.scatter(x2,T)

plt.xlabel('Concentration x')
plt.ylabel('Temperature/K')
plt.xlim(0,1)
plt.ylim(ymin=0)
plt.show()

